# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeSeries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitedata',
            name='satellite',
            field=models.CharField(choices=[('TRMMSatelliteRainfall', 'TRMM 3B42 3h')], default='TRMMSatelliteRainfall', help_text='Choice among supported satellite products.', max_length=255, verbose_name='Satellite product'),
        ),
    ]
