# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:23
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeSeries', '0002_auto_20160705_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitedata',
            name='geometry',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/zepedro/Tethys/timeSeries'), upload_to='static/timeSeries/satelliteDataGeometries/'),
        ),
    ]
