# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeSeries', '0003_auto_20160705_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitedata',
            name='timestep',
            field=models.CharField(max_length=255),
        ),
    ]
