# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeSeries', '0004_auto_20160706_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellitedata',
            name='latitudes',
        ),
        migrations.RemoveField(
            model_name='satellitedata',
            name='longitudes',
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='jsonGeometry',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='readyGeometry',
            field=models.BooleanField(default=False, verbose_name='Geometry ready'),
        ),
    ]
