# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeSeries', '0007_auto_20160707_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellitedata',
            name='downloadFolder',
        ),
    ]
