# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 09:08
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeSeries', '0008_remove_satellitedata_downloadfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellitedata',
            name='readyGeometry',
        ),
        migrations.AlterField(
            model_name='satellitedata',
            name='dataFolder',
            field=models.CharField(default='/home/zepedro/Tethys/timeSeries/satelliteData/data/__unknonwn__', max_length=255),
        ),
        migrations.AlterField(
            model_name='satellitedata',
            name='geometry',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/zepedro/Tethys/timeSeries'), upload_to='static/timeSeries/satelliteData/geometries/'),
        ),
    ]
