# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeSeries', '0009_auto_20160708_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colormap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('geometry', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/zepedro/Tethys/timeSeries'), upload_to='static/timeSeries/colormaps/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('introducedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Introduced by')),
            ],
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='colormap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timeSeries.Colormap'),
        ),
    ]
