# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeSeries', '0010_auto_20160719_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colormap',
            old_name='geometry',
            new_name='file',
        ),
    ]
